Refactoring + shuffling & sampling
rodrigodelazcano/Minari pull request #1
Opened 2023-03-03 16:08 UTC by younik

I tried to refactor a bit the Minari.

Most notably, there is a new class `MinariStorage` that handles access to the file, while `MinariDataset` should delegate to it; `MinariDataset` can point to a slice of `MinariStorage`.

I implemented the shuffle & sampling method as returning a new `MinariDataset` pointing to the same `MinariStorage`. 
There is an `iter` method to iterate over the dataset.

#### TODO
- [ ]  Fix `update_dataset_from_collector_env` & `update_dataset_from_buffer`
- [ ]  Implement `MinariDataset.total_steps`
- [ ]  Use a class for Episode data instead of h5py.Group

2023-03-16 02:13 UTC, rodrigodelazcano requested changes
I think that the refactored implementation looks good. Just a couple of comments before merging.

Also, we should give access to the dataset metadata through `MinariDataset` instead of keeping it in `MinariStorage`. My suggestion is to create a `MinariDatasetSpec` attribute which contains all the metadata and can be accessed as `dataset.spec`, similar to the Gymnasium `env.spec`. We can do this in a separate PR.

2023-03-16 02:13 UTC, rodrigodelazcano commented on minari/utils.py
> +    assert sum(sizes) <= dataset.total_episodes
Add an assertion comment

2023-03-16 02:13 UTC, rodrigodelazcano commented on minari/utils.py
> +def split_dataset(dataset: MinariDataset, sizes: List[int], seed=None) -> List[MinariDataset]:
Add docstrings for the function

2023-03-16 02:13 UTC, rodrigodelazcano commented on minari/minari_dataset.py
>          """Initialize properties of the Minari Dataset.
Update docstrings

2023-03-16 02:13 UTC, rodrigodelazcano commented on minari/minari_dataset.py
> +            self._data = MinariStorage(data)
Can we also raise an error if `data` is non of the allowed types?

2023-03-16 02:13 UTC, rodrigodelazcano commented on minari/minari_dataset.py
> +    def total_steps(self):
Can we compute the total number of steps when we create a new MinariDataset object? This is the fastest solution I can think of as for now, since we can modify the size of the dataset with slicing and filtering

2023-03-16 02:13 UTC, rodrigodelazcano commented on minari/minari_storage.py
> +            self._flatten_actions = f.attrs["flatten_action"]
The user should have access to these attributes through `MinariDataset`. I suggest having a `MinaraDatasetSpec` attribute that contains all of these attributes and that is accessible through `MinariDataset`. We can do this in a later PR

2023-03-16 02:13 UTC, rodrigodelazcano commented on minari/minari_storage.py
> +    def apply(
Add docstrings

2023-03-16 02:13 UTC, rodrigodelazcano commented on minari/minari_storage.py
> +    def get_episodes(self, episode_indices: Iterable) -> List[dict]:
Add docstrings

2023-03-16 02:14 UTC, rodrigodelazcano commented
@younik  can you also fix the CI errors?

2023-03-16 22:59 UTC, younik commented on minari/minari_dataset.py
> +    def total_steps(self):
I thought computing the `total_steps` could be computationally expensive and most of the time is not needed, thus a lazy initialization seemed more suitable

Anyway, for this alpha release, we can do the simplest thing and engineer it later

2023-03-19 17:30 UTC, rodrigodelazcano commented on minari/minari_dataset.py
> +    def total_steps(self):
Yes I agree. We should figure out performance issues later.

2023-03-19 17:30 UTC, rodrigodelazcano approved these changes
LGTM. I'm going to merge this :)

2023-03-19 17:37 UTC, merged